---- CREATE TABLE ----
CREATE TABLE CLOTHING_SALES(
ORDERID INT PRIMARY KEY,
ORDERDATE DATE,
CITY VARCHAR(20),
CATEGORY VARCHAR(20),
PRODUCT VARCHAR(20),
QUANTITY INT,
PRICE INT,
DISCOUNT_PERCENT INT,
CUSTOMER_TYPE VARCHAR(20)
);

---- INSERT VALUES INTO TABLE-----

INSERT INTO CLOTHING_SALES VALUES
(7001,'2026-03-15','DELHI','MEN','T-SHIRT',2,800,10,'NEW'),
(7002,'2026-03-15','MUMBAI','WOMEN','DRESS',1,1500,15,'RETURNING'),
(7003,'2026-03-16','BANGALORE','MEN','JEANS',1,2000,20,'NEW'),
(7004,'2026-03-16','DELHI','KIDS','SHORTS',3,500,5,'RETURNING'),
(7005,'2026-03-17','HYDERABAD','WOMEN','TOP',2,900,10,'NEW'),
(7006,'2026-03-17','MUMBAI','MEN','SHIRT',1,1200,0,'RETURNING'),
(7007,'2026-03-18','BANGALORE','WOMEN','SKIRT',2,1100,15,'NEW'),
(7008,'2026-03-18','HYDERABAD','KIDS','T-SHIRT',2,600,5,'RETURNING'),
(7009,'2026-03-19','DELHI','MEN','JEANS',1,2100,20,'NEW'),
(7010,'2026-03-19','MUMBAI','WOMEN','DRESS',1,1600,10,'RETURNING')

---- SEE FULL DATA ----

SELECT * FROM CLOTHING_SALES;

---- REVENUE CALCULATION -----

SELECT 
  SUM(QUANTITY*(PRICE - (PRICE*DISCOUNT_PERCENT/100))) AS TOTAL_REVENUE
FROM CLOTHING_SALES;

---- REVENUE BY CATEGORY ----

SELECT 
  CATEGORY,
  SUM(QUANTITY*(PRICE - (PRICE*DISCOUNT_PERCENT/100))) AS TOTAL_REVENUE
FROM CLOTHING_SALES
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE DESC;

---- DISCOUNT IMPACT ----

SELECT 
  DISCOUNT_PERCENT,
  SUM(QUANTITY) AS TOTAL_UNITS
FROM CLOTHING_SALES
GROUP BY DISCOUNT_PERCENT
ORDER BY DISCOUNT_PERCENT DESC;

---- REVENUE BY CITY ----

SELECT 
  CITY, 
  SUM(QUANTITY*(PRICE - (PRICE*DISCOUNT_PERCENT/100))) AS TOTAL_REVENUE
FROM CLOTHING_SALES
GROUP BY CITY
ORDER BY TOTAL_REVENUE DESC;

---- REVENUE BY PRODUCT ----

SELECT 
  PRODUCT,
  SUM(QUANTITY*(PRICE - (PRICE*DISCOUNT_PERCENT/100))) AS TOTAL_REVENUE
FROM CLOTHING_SALES
GROUP BY PRODUCT
ORDER BY TOTAL_REVENUE DESC;

---- REVENUE BY CUSTOMER_TYPE ----

SELECT 
  CUSTOMER_TYPE,
  SUM(QUANTITY*(PRICE - (PRICE*DISCOUNT_PERCENT/100))) AS TOTAL_REVENUE
FROM CLOTHING_SALES
GROUP BY CUSTOMER_TYPE
ORDER BY TOTAL_REVENUE DESC;

